#!/bin/sh

sample_text="Global variable"

foo(){
 local sample_text="Local variable"
 echo "Inside function"
 echo $sample_text
}

echo "script starting"
echo $sample_text

foo

echo "script ended"
echo $sample_text

exit 0
